/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/app'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppAlertsRouteImport } from './routes/app.alerts'
import { Route as AppAssessmentsRouteImport } from './routes/app.assessments'
import { Route as AppBlocklistRouteImport } from './routes/app.blocklist'
import { Route as AppComplianceRouteImport } from './routes/app.compliance'
import { Route as AppCopilotRouteImport } from './routes/app.copilot'
import { Route as AppDashboardRouteImport } from './routes/app.dashboard'
import { Route as AppDevicesRouteImport } from './routes/app.devices'
import { Route as AppSessionsRouteImport } from './routes/app.sessions'
import { Route as AppSettingsRouteImport } from './routes/app.settings'
import { Route as AppSimulatorRouteImport } from './routes/app.simulator'
import { Route as AppThreatsRouteImport } from './routes/app.threats'
import { Route as AppUbaRouteImport } from './routes/app.uba'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppAlertsRoute = AppAlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => AppRoute,
} as any)
const AppAssessmentsRoute = AppAssessmentsRouteImport.update({
  id: '/assessments',
  path: '/assessments',
  getParentRoute: () => AppRoute,
} as any)
const AppBlocklistRoute = AppBlocklistRouteImport.update({
  id: '/blocklist',
  path: '/blocklist',
  getParentRoute: () => AppRoute,
} as any)
const AppComplianceRoute = AppComplianceRouteImport.update({
  id: '/compliance',
  path: '/compliance',
  getParentRoute: () => AppRoute,
} as any)
const AppCopilotRoute = AppCopilotRouteImport.update({
  id: '/copilot',
  path: '/copilot',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppDevicesRoute = AppDevicesRouteImport.update({
  id: '/devices',
  path: '/devices',
  getParentRoute: () => AppRoute,
} as any)
const AppSessionsRoute = AppSessionsRouteImport.update({
  id: '/sessions',
  path: '/sessions',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppSimulatorRoute = AppSimulatorRouteImport.update({
  id: '/simulator',
  path: '/simulator',
  getParentRoute: () => AppRoute,
} as any)
const AppThreatsRoute = AppThreatsRouteImport.update({
  id: '/threats',
  path: '/threats',
  getParentRoute: () => AppRoute,
} as any)
const AppUbaRoute = AppUbaRouteImport.update({
  id: '/uba',
  path: '/uba',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/app/alerts': typeof AppAlertsRoute
  '/app/assessments': typeof AppAssessmentsRoute
  '/app/blocklist': typeof AppBlocklistRoute
  '/app/compliance': typeof AppComplianceRoute
  '/app/copilot': typeof AppCopilotRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/devices': typeof AppDevicesRoute
  '/app/sessions': typeof AppSessionsRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/simulator': typeof AppSimulatorRoute
  '/app/threats': typeof AppThreatsRoute
  '/app/uba': typeof AppUbaRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/app/alerts': typeof AppAlertsRoute
  '/app/assessments': typeof AppAssessmentsRoute
  '/app/blocklist': typeof AppBlocklistRoute
  '/app/compliance': typeof AppComplianceRoute
  '/app/copilot': typeof AppCopilotRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/devices': typeof AppDevicesRoute
  '/app/sessions': typeof AppSessionsRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/simulator': typeof AppSimulatorRoute
  '/app/threats': typeof AppThreatsRoute
  '/app/uba': typeof AppUbaRoute
  '/app': typeof AppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/app/alerts': typeof AppAlertsRoute
  '/app/assessments': typeof AppAssessmentsRoute
  '/app/blocklist': typeof AppBlocklistRoute
  '/app/compliance': typeof AppComplianceRoute
  '/app/copilot': typeof AppCopilotRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/devices': typeof AppDevicesRoute
  '/app/sessions': typeof AppSessionsRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/simulator': typeof AppSimulatorRoute
  '/app/threats': typeof AppThreatsRoute
  '/app/uba': typeof AppUbaRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/auth'
    | '/app/alerts'
    | '/app/assessments'
    | '/app/blocklist'
    | '/app/compliance'
    | '/app/copilot'
    | '/app/dashboard'
    | '/app/devices'
    | '/app/sessions'
    | '/app/settings'
    | '/app/simulator'
    | '/app/threats'
    | '/app/uba'
    | '/app/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/app/alerts'
    | '/app/assessments'
    | '/app/blocklist'
    | '/app/compliance'
    | '/app/copilot'
    | '/app/dashboard'
    | '/app/devices'
    | '/app/sessions'
    | '/app/settings'
    | '/app/simulator'
    | '/app/threats'
    | '/app/uba'
    | '/app'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/auth'
    | '/app/alerts'
    | '/app/assessments'
    | '/app/blocklist'
    | '/app/compliance'
    | '/app/copilot'
    | '/app/dashboard'
    | '/app/devices'
    | '/app/sessions'
    | '/app/settings'
    | '/app/simulator'
    | '/app/threats'
    | '/app/uba'
    | '/app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/alerts': {
      id: '/app/alerts'
      path: '/alerts'
      fullPath: '/app/alerts'
      preLoaderRoute: typeof AppAlertsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/assessments': {
      id: '/app/assessments'
      path: '/assessments'
      fullPath: '/app/assessments'
      preLoaderRoute: typeof AppAssessmentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/blocklist': {
      id: '/app/blocklist'
      path: '/blocklist'
      fullPath: '/app/blocklist'
      preLoaderRoute: typeof AppBlocklistRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/compliance': {
      id: '/app/compliance'
      path: '/compliance'
      fullPath: '/app/compliance'
      preLoaderRoute: typeof AppComplianceRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/copilot': {
      id: '/app/copilot'
      path: '/copilot'
      fullPath: '/app/copilot'
      preLoaderRoute: typeof AppCopilotRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/dashboard': {
      id: '/app/dashboard'
      path: '/dashboard'
      fullPath: '/app/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/devices': {
      id: '/app/devices'
      path: '/devices'
      fullPath: '/app/devices'
      preLoaderRoute: typeof AppDevicesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/sessions': {
      id: '/app/sessions'
      path: '/sessions'
      fullPath: '/app/sessions'
      preLoaderRoute: typeof AppSessionsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/simulator': {
      id: '/app/simulator'
      path: '/simulator'
      fullPath: '/app/simulator'
      preLoaderRoute: typeof AppSimulatorRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/threats': {
      id: '/app/threats'
      path: '/threats'
      fullPath: '/app/threats'
      preLoaderRoute: typeof AppThreatsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/uba': {
      id: '/app/uba'
      path: '/uba'
      fullPath: '/app/uba'
      preLoaderRoute: typeof AppUbaRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAlertsRoute: typeof AppAlertsRoute
  AppAssessmentsRoute: typeof AppAssessmentsRoute
  AppBlocklistRoute: typeof AppBlocklistRoute
  AppComplianceRoute: typeof AppComplianceRoute
  AppCopilotRoute: typeof AppCopilotRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppDevicesRoute: typeof AppDevicesRoute
  AppSessionsRoute: typeof AppSessionsRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppSimulatorRoute: typeof AppSimulatorRoute
  AppThreatsRoute: typeof AppThreatsRoute
  AppUbaRoute: typeof AppUbaRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAlertsRoute: AppAlertsRoute,
  AppAssessmentsRoute: AppAssessmentsRoute,
  AppBlocklistRoute: AppBlocklistRoute,
  AppComplianceRoute: AppComplianceRoute,
  AppCopilotRoute: AppCopilotRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppDevicesRoute: AppDevicesRoute,
  AppSessionsRoute: AppSessionsRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppSimulatorRoute: AppSimulatorRoute,
  AppThreatsRoute: AppThreatsRoute,
  AppUbaRoute: AppUbaRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
